import { ViralTemplate } from "./types";

// ===== バズ動画テンプレートライブラリ =====
// 実際のバズ動画パターンを分析して作成。日々追加されていく蓄積型データベース。

export const VIRAL_TEMPLATES: ViralTemplate[] = [

  // ==========================================
  // 腰痛
  // ==========================================
  {
    id: "lbp-selfcare-30s",
    name: "腰痛が30秒で楽になるセルフケア",
    description: "最もバズりやすい王道フォーマット。短時間で効果を体感できるセルフケア動画。",
    symptom: "腰痛",
    platform: "reels",
    format: "セルフケア指導",
    buzzScore: 5,
    referenceNote: "治療院Reelsの王道パターン。10万再生超え多数",
    titlePattern: "腰痛が{期間}で楽になる！{手法}をプロが教えます",
    hookLine: "この動画を見ている間に腰痛が楽になります。騙されたと思ってやってみてください。",
    scriptStructure: [
      { type: "hook", text: "この動画を見ている間に腰痛が楽になります", duration: 3, note: "カメラ目線、断言する" },
      { type: "problem", text: "朝起きた時、腰が重い・痛いと感じていませんか？", duration: 4, note: "共感を誘う表情" },
      { type: "solution", text: "実は腰痛の原因の8割はお尻の筋肉にあります", duration: 5, note: "指でお尻を指す" },
      { type: "demonstration", text: "このストレッチを30秒やるだけ。まず仰向けに寝て...", duration: 30, note: "実演。テロップで手順を出す" },
      { type: "bridge", text: "どうですか？腰が軽くなりましたよね", duration: 3, note: "笑顔で確認" },
      { type: "cta", text: "もっと詳しく知りたい方はプロフィールのリンクから", duration: 5, note: "プロフィールを指差す" },
    ],
    thumbnailTips: "施術者がストレッチのポーズ + 「腰痛30秒で消える」の大文字テロップ + 赤い矢印で腰を指す",
    hashtagStrategy: ["#腰痛", "#腰痛改善", "#ストレッチ", "#セルフケア", "#整体", "#腰痛ストレッチ", "#朝の腰痛"],
    captionTemplate: "【腰痛が30秒で楽になるストレッチ】\n\n朝起きると腰が重い...😢\nそんなお悩みありませんか？\n\n実は腰痛の原因の多くは「お尻の筋肉」にあります。\n\nこの簡単ストレッチを毎朝30秒やるだけで\n腰の軽さが全然変わります✨\n\n保存して明日の朝やってみてください！",
    recommendedDuration: { min: 30, max: 60 },
    aspectRatio: "9:16",
    tags: ["王道", "初心者向け", "セルフケア", "高再生"],
    createdAt: "2026-03-28",
    updatedAt: "2026-03-28",
  },
  {
    id: "lbp-ng-action",
    name: "腰痛を悪化させるNG行動3選",
    description: "「やってはいけない」系は好奇心を刺激してバズりやすい。",
    symptom: "腰痛",
    platform: "reels",
    format: "NG行動",
    buzzScore: 5,
    referenceNote: "NG系・警告系コンテンツは保存率が高い",
    titlePattern: "【危険】腰痛の人が絶対やってはいけない{数}つのこと",
    hookLine: "腰痛の人がやりがちなこの3つ、今すぐやめてください。",
    scriptStructure: [
      { type: "hook", text: "腰痛の人がやりがちなこの3つ、今すぐやめてください", duration: 3, note: "真剣な表情、手でバツ" },
      { type: "problem", text: "1つ目：腰を反らすストレッチ。実はこれ逆効果なんです", duration: 8, note: "NG動作を見せてバツマーク" },
      { type: "problem", text: "2つ目：長時間の安静。動かないと余計に固まります", duration: 8, note: "ソファでダラダラのイメージ" },
      { type: "problem", text: "3つ目：シップだけで済ませる。痛みを隠しているだけです", duration: 8, note: "シップを見せる" },
      { type: "solution", text: "じゃあ何をすればいいか？答えはプロフィールのリンクで", duration: 3, note: "CTA" },
    ],
    thumbnailTips: "驚いた表情 + 大きなバツマーク + 「絶対やるな」のテロップ（赤文字）",
    hashtagStrategy: ["#腰痛", "#腰痛改善", "#やってはいけない", "#NG行動", "#整体師が教える"],
    captionTemplate: "【腰痛を悪化させるNG行動3選】\n\n良かれと思ってやっていること、\n実は腰痛を悪化させているかも⚠️\n\n1️⃣ 腰を反らすストレッチ\n2️⃣ 長時間の安静\n3️⃣ シップだけで済ませる\n\n正しい対処法が気になる方は\nお気軽にご相談ください！",
    recommendedDuration: { min: 30, max: 60 },
    aspectRatio: "9:16",
    tags: ["NG系", "警告", "保存率高い"],
    createdAt: "2026-03-28",
    updatedAt: "2026-03-28",
  },
  {
    id: "lbp-youtube-explain",
    name: "【完全版】腰痛の原因と治し方",
    description: "YouTube長尺の解説動画。SEOで安定的に再生数が伸びるストック型コンテンツ。",
    symptom: "腰痛",
    platform: "youtube",
    format: "症状解説",
    buzzScore: 4,
    referenceNote: "検索流入メイン。「腰痛 治し方」で上位表示を狙う",
    titlePattern: "【完全版】{症状}の原因と治し方｜{肩書き}が徹底解説",
    hookLine: "この動画を最後まで見れば、あなたの腰痛の原因がわかります。",
    scriptStructure: [
      { type: "hook", text: "この動画を最後まで見れば、あなたの腰痛の原因がわかります", duration: 5, note: "カメラ目線で自信を持って" },
      { type: "bridge", text: "こんにちは。{院名}の{先生名}です。今日は腰痛について徹底的に解説します", duration: 10, note: "自己紹介+チャンネル登録促進" },
      { type: "problem", text: "腰痛には大きく分けて3つのタイプがあります", duration: 60, note: "図やイラストを使って解説" },
      { type: "solution", text: "タイプ別の対処法をお伝えします", duration: 120, note: "各タイプの改善法を実演" },
      { type: "demonstration", text: "今すぐできるセルフチェック法", duration: 60, note: "視聴者参加型" },
      { type: "cta", text: "概要欄から予約できます。チャンネル登録もお願いします", duration: 10, note: "エンドカード" },
    ],
    thumbnailTips: "施術者の顔 + 腰を押さえるイラスト + 「9割の人が間違えている」等の煽りテキスト",
    hashtagStrategy: ["#腰痛", "#腰痛改善", "#腰痛治し方", "#整体", "#ストレッチ"],
    captionTemplate: "【腰痛の原因と治し方を徹底解説】\n\n腰痛には3つのタイプがあり、\nそれぞれ対処法が違います。\n\n間違った対処をすると悪化することも...\n\n▼目次\n0:00 はじめに\n0:15 腰痛の3タイプ\n1:15 タイプ別の対処法\n3:15 セルフチェック法\n4:15 まとめ\n\n▼ご予約はこちら\n{予約URL}",
    recommendedDuration: { min: 180, max: 420 },
    aspectRatio: "16:9",
    tags: ["SEO", "検索流入", "ストック型", "長尺"],
    createdAt: "2026-03-28",
    updatedAt: "2026-03-28",
  },

  // ==========================================
  // 肩こり
  // ==========================================
  {
    id: "stiff-shoulder-desk",
    name: "デスクワーカーの肩こり解消ストレッチ",
    description: "ターゲットを絞ることで刺さる。「デスクワーク」はバズワード。",
    symptom: "肩こり",
    platform: "reels",
    format: "セルフケア指導",
    buzzScore: 5,
    referenceNote: "「デスクワーク 肩こり」はReelsで最も伸びるテーマの一つ",
    titlePattern: "デスクワーカー必見！肩こりが{期間}で楽になる方法",
    hookLine: "デスクワークの肩こりに悩んでる人、この動画保存してください。",
    scriptStructure: [
      { type: "hook", text: "デスクワークで肩がガチガチの人、保存してください", duration: 3, note: "肩を回して辛そうな表情→真顔" },
      { type: "problem", text: "パソコン作業で肩が前に出ると、僧帽筋がずっと引っ張られて固まります", duration: 5, note: "デスクで作業する姿勢を再現" },
      { type: "demonstration", text: "このストレッチを仕事の合間に1分やるだけ", duration: 35, note: "椅子に座ったまま可能なストレッチ3つ" },
      { type: "bridge", text: "肩の可動域が全然違うのわかりますか？", duration: 3, note: "ビフォーアフターで肩を回す" },
      { type: "cta", text: "保存して仕事の合間にやってみてね", duration: 4, note: "保存ボタンを指差す" },
    ],
    thumbnailTips: "PCの前で肩を押さえる人 + 「肩こり1分で解消」テロップ + 矢印",
    hashtagStrategy: ["#肩こり", "#肩こり解消", "#デスクワーク", "#ストレッチ", "#オフィスストレッチ", "#肩こりストレッチ"],
    captionTemplate: "【デスクワーカーの肩こり1分解消法】\n\nパソコン作業で肩がバキバキ…\nそんな人のための簡単ストレッチ💻\n\n✅ 椅子に座ったままできる\n✅ 1分で終わる\n✅ 仕事の合間にサッとできる\n\n保存して毎日やってみてください！",
    recommendedDuration: { min: 30, max: 60 },
    aspectRatio: "9:16",
    tags: ["デスクワーク", "オフィス", "保存推奨"],
    createdAt: "2026-03-28",
    updatedAt: "2026-03-28",
  },
  {
    id: "stiff-shoulder-ranking",
    name: "肩こりに効くツボBEST5",
    description: "ランキング形式は最後まで見てもらえる。視聴完了率が高い。",
    symptom: "肩こり",
    platform: "shorts",
    format: "ランキング",
    buzzScore: 4,
    referenceNote: "ランキング形式はショート動画で視聴完了率が高い",
    titlePattern: "{症状}に効くツボBEST{数}｜{肩書き}が厳選",
    hookLine: "肩こりに効くツボ、5位から発表します。",
    scriptStructure: [
      { type: "hook", text: "肩こりに効くツボ、5位から発表します", duration: 3, note: "ランキング画面を見せる" },
      { type: "demonstration", text: "第5位：風池（ふうち）首の付け根のここです", duration: 8, note: "ツボの位置を実演" },
      { type: "demonstration", text: "第4位：肩井（けんせい）肩の真ん中のここ", duration: 8, note: "" },
      { type: "demonstration", text: "第3位：天柱（てんちゅう）後頭部の2本の筋の外側", duration: 8, note: "" },
      { type: "demonstration", text: "第2位：合谷（ごうこく）手の親指と人差し指の間", duration: 8, note: "意外性でフック" },
      { type: "demonstration", text: "第1位：中府（ちゅうふ）鎖骨の下のここを押してみて", duration: 10, note: "1位は意外なツボで驚き" },
      { type: "cta", text: "いいねと保存で次回もお届けします", duration: 5, note: "" },
    ],
    thumbnailTips: "「肩こりツボBEST5」+ 数字を大きく + ツボを押している手のアップ",
    hashtagStrategy: ["#肩こり", "#ツボ", "#セルフケア", "#ランキング", "#東洋医学", "#肩こり解消"],
    captionTemplate: "【肩こりに効くツボBEST5】\n\n5位 風池\n4位 肩井\n3位 天柱\n2位 合谷\n1位 ???（動画を見てね）\n\n1位は意外なあのツボ！\n動画で場所と押し方を解説しています👆",
    recommendedDuration: { min: 40, max: 60 },
    aspectRatio: "9:16",
    tags: ["ランキング", "ツボ", "視聴完了率高い"],
    createdAt: "2026-03-28",
    updatedAt: "2026-03-28",
  },

  // ==========================================
  // 頭痛
  // ==========================================
  {
    id: "headache-instant-relief",
    name: "頭痛がその場で楽になるセルフケア",
    description: "「今すぐ楽にしたい」ニーズが強い症状。即効性訴求がバズる。",
    symptom: "頭痛",
    platform: "reels",
    format: "セルフケア指導",
    buzzScore: 5,
    referenceNote: "頭痛系は「即効性」がキーワード。薬に頼りたくない層に刺さる",
    titlePattern: "薬を使わずに頭痛を{期間}で和らげる方法",
    hookLine: "頭痛が辛い時、薬を飲む前にこれを試してみてください。",
    scriptStructure: [
      { type: "hook", text: "頭痛が辛い時、薬を飲む前にこれやって", duration: 3, note: "頭を押さえながら→真剣な顔に" },
      { type: "problem", text: "頭痛の多くは首や肩の筋肉の緊張が原因です", duration: 5, note: "首を触りながら" },
      { type: "demonstration", text: "このツボを10秒押すだけ。後頭部のここ、風池というツボです", duration: 25, note: "ツボの位置をアップで見せる" },
      { type: "bridge", text: "頭がスーッと軽くなりませんか？", duration: 3, note: "楽になった表情" },
      { type: "cta", text: "頭痛持ちの人は保存しておいてね", duration: 4, note: "" },
    ],
    thumbnailTips: "こめかみを押さえる + 「薬なしで頭痛が消える」テロップ + ビフォーアフター矢印",
    hashtagStrategy: ["#頭痛", "#頭痛解消", "#偏頭痛", "#薬に頼らない", "#セルフケア", "#ツボ押し"],
    captionTemplate: "【薬なしで頭痛を楽にする方法】\n\n頭痛が来た時、すぐ薬に手が伸びていませんか？\n\n実は後頭部の「風池」というツボを\n10秒押すだけで楽になることがあります💡\n\n薬に頼りたくない人は\nぜひ試してみてください！",
    recommendedDuration: { min: 30, max: 50 },
    aspectRatio: "9:16",
    tags: ["即効性", "薬不要", "ツボ"],
    createdAt: "2026-03-28",
    updatedAt: "2026-03-28",
  },
  {
    id: "headache-type-explain",
    name: "あなたの頭痛はどのタイプ？見分け方",
    description: "診断・分類系はエンゲージメントが高い。自分事化しやすい。",
    symptom: "頭痛",
    platform: "youtube",
    format: "症状解説",
    buzzScore: 4,
    referenceNote: "「頭痛 種類」の検索ボリュームが大きい",
    titlePattern: "あなたの頭痛はどれ？{数}つのタイプ別原因と対処法",
    hookLine: "あなたの頭痛、3種類のうちどれか知っていますか？間違った対処をすると悪化します。",
    scriptStructure: [
      { type: "hook", text: "あなたの頭痛は3種類のうちどれですか？間違った対処をすると悪化します", duration: 5, note: "3つの選択肢を画面に表示" },
      { type: "bridge", text: "こんにちは、{院名}の{先生名}です。今日は頭痛のタイプを徹底解説します", duration: 8, note: "" },
      { type: "problem", text: "1. 緊張型頭痛：頭全体が締め付けられる感じ。デスクワークや姿勢の悪さが原因", duration: 40, note: "イラスト+症状チェックリスト" },
      { type: "problem", text: "2. 片頭痛：ズキズキ脈打つような痛み。光や音に敏感になる", duration: 40, note: "" },
      { type: "problem", text: "3. 群発頭痛：目の奥が激しく痛む。男性に多い", duration: 30, note: "" },
      { type: "solution", text: "タイプ別の正しい対処法", duration: 60, note: "" },
      { type: "cta", text: "どのタイプかわからない方はお気軽にご相談ください", duration: 10, note: "" },
    ],
    thumbnailTips: "頭を3分割して色分け + 「あなたはどれ？」テロップ + 驚きの表情",
    hashtagStrategy: ["#頭痛", "#偏頭痛", "#緊張型頭痛", "#頭痛の種類", "#セルフチェック"],
    captionTemplate: "【あなたの頭痛はどのタイプ？】\n\n頭痛には主に3つのタイプがあります。\n\n1️⃣ 緊張型頭痛 → 締め付けられる\n2️⃣ 片頭痛 → ズキズキ脈打つ\n3️⃣ 群発頭痛 → 目の奥が激痛\n\nタイプが違えば対処法も違います。\n間違った対処で悪化させないために\nまずは自分のタイプを知りましょう💡",
    recommendedDuration: { min: 180, max: 360 },
    aspectRatio: "16:9",
    tags: ["分類系", "教育", "SEO"],
    createdAt: "2026-03-28",
    updatedAt: "2026-03-28",
  },

  // ==========================================
  // 自律神経
  // ==========================================
  {
    id: "autonomic-morning-routine",
    name: "自律神経を整える朝の3分ルーティン",
    description: "「朝ルーティン」は全SNSで人気フォーマット。自律神経と相性抜群。",
    symptom: "自律神経",
    platform: "reels",
    format: "セルフケア指導",
    buzzScore: 5,
    referenceNote: "「朝ルーティン × 自律神経」は最もバズるテーマの一つ",
    titlePattern: "自律神経が整う朝の{期間}ルーティン",
    hookLine: "自律神経が乱れている人、朝起きてすぐこの3つをやってください。",
    scriptStructure: [
      { type: "hook", text: "自律神経が乱れてる人、朝この3つやって", duration: 3, note: "3本指を立てる" },
      { type: "problem", text: "朝だるい、やる気が出ない、それは自律神経の乱れかも", duration: 4, note: "共感の表情" },
      { type: "demonstration", text: "1つ目：起きたらまず日光を浴びる。窓を開けて10秒でOK", duration: 10, note: "カーテンを開けるシーン" },
      { type: "demonstration", text: "2つ目：白湯を1杯飲む。内臓が温まって副交感神経が活性化", duration: 10, note: "白湯を注ぐシーン" },
      { type: "demonstration", text: "3つ目：この深呼吸を5回。4秒吸って8秒吐く", duration: 15, note: "呼吸法の実演" },
      { type: "cta", text: "これを1週間続けると体が変わります。保存して明日から", duration: 5, note: "" },
    ],
    thumbnailTips: "朝日 + ヨガっぽいポーズ + 「自律神経が整う朝習慣」テロップ",
    hashtagStrategy: ["#自律神経", "#自律神経を整える", "#朝ルーティン", "#モーニングルーティン", "#セルフケア", "#健康習慣"],
    captionTemplate: "【自律神経を整える朝3分ルーティン】\n\n朝だるい、やる気が出ない...\nそれは自律神経の乱れサインかも💡\n\n①日光を浴びる（10秒でOK）\n②白湯を1杯\n③深呼吸5回（4秒吸って8秒吐く）\n\nたった3分で体が変わります✨\n保存して明日からやってみて！",
    recommendedDuration: { min: 40, max: 60 },
    aspectRatio: "9:16",
    tags: ["朝ルーティン", "習慣化", "シリーズ化向き"],
    createdAt: "2026-03-28",
    updatedAt: "2026-03-28",
  },
  {
    id: "autonomic-check",
    name: "自律神経の乱れセルフチェック",
    description: "セルフチェック系はコメント・保存が多くバズりやすい。",
    symptom: "自律神経",
    platform: "tiktok",
    format: "あるある共感",
    buzzScore: 5,
    referenceNote: "チェックリスト系は共感・コメントでアルゴリズムに乗りやすい",
    titlePattern: "{数}個以上当てはまったら自律神経が乱れてます",
    hookLine: "3個以上当てはまったら自律神経が乱れてる可能性があります。チェックしてみて。",
    scriptStructure: [
      { type: "hook", text: "3個以上当てはまったら自律神経乱れてます。チェック", duration: 3, note: "指折りカウントの準備" },
      { type: "demonstration", text: "1. 朝起きるのがつらい", duration: 3, note: "テロップで表示" },
      { type: "demonstration", text: "2. 寝ても疲れが取れない", duration: 3, note: "" },
      { type: "demonstration", text: "3. 急に動悸がする", duration: 3, note: "" },
      { type: "demonstration", text: "4. 手足が冷たい", duration: 3, note: "" },
      { type: "demonstration", text: "5. 天気が悪い日は体調も悪い", duration: 3, note: "" },
      { type: "demonstration", text: "6. 食欲にムラがある", duration: 3, note: "" },
      { type: "demonstration", text: "7. イライラしやすい", duration: 3, note: "" },
      { type: "bridge", text: "何個当てはまりましたか？コメントで教えて", duration: 5, note: "コメント促進" },
      { type: "cta", text: "改善法は次の動画で紹介します。フォローして待っててね", duration: 5, note: "シリーズ化の伏線" },
    ],
    thumbnailTips: "チェックリスト風 + 赤い数字「7つのサイン」+ 心配そうな表情",
    hashtagStrategy: ["#自律神経", "#セルフチェック", "#自律神経の乱れ", "#体調不良", "#健康チェック"],
    captionTemplate: "【自律神経の乱れチェック】\n\n3個以上当てはまったら要注意⚠️\n\n☐ 朝起きるのがつらい\n☐ 寝ても疲れが取れない\n☐ 急に動悸がする\n☐ 手足が冷たい\n☐ 天気が悪い日は不調\n☐ 食欲にムラがある\n☐ イライラしやすい\n\n何個当てはまった？コメントで教えて👇",
    recommendedDuration: { min: 30, max: 45 },
    aspectRatio: "9:16",
    tags: ["チェック系", "コメント促進", "シリーズ化"],
    createdAt: "2026-03-28",
    updatedAt: "2026-03-28",
  },

  // ==========================================
  // 膝痛
  // ==========================================
  {
    id: "knee-stair-pain",
    name: "階段で膝が痛い人のセルフケア",
    description: "具体的なシーンで切り取ると「自分のことだ」と思わせられる。",
    symptom: "膝痛",
    platform: "reels",
    format: "セルフケア指導",
    buzzScore: 4,
    referenceNote: "「階段 膝痛」は高齢者のリアルな悩み。中高年層の保存率が高い",
    titlePattern: "階段で膝が痛い人、この筋肉をほぐしてみて",
    hookLine: "階段を降りる時に膝が痛い人。原因はここです。",
    scriptStructure: [
      { type: "hook", text: "階段降りる時に膝が痛い人。原因はここ", duration: 3, note: "太ももの前を指す" },
      { type: "problem", text: "膝の痛みの原因の多くは太ももの前の筋肉、大腿四頭筋が固まっていることです", duration: 6, note: "筋肉の位置を説明" },
      { type: "demonstration", text: "このほぐし方を毎日やってみてください", duration: 30, note: "テニスボールを使ったセルフマッサージ" },
      { type: "bridge", text: "ほぐした後に足踏みしてみてください。軽くないですか？", duration: 5, note: "体感の確認" },
      { type: "cta", text: "膝で悩んでいる人はフォローしてね", duration: 4, note: "" },
    ],
    thumbnailTips: "階段を降りる足のアップ + 膝に赤い印 + 「この筋肉が原因」テロップ",
    hashtagStrategy: ["#膝痛", "#膝痛改善", "#階段", "#セルフケア", "#50代", "#60代"],
    captionTemplate: "【階段で膝が痛い人必見】\n\n階段を降りる時に膝がズキッとする…\nそんな方は太ももの前の筋肉が\nカチカチになっていませんか？\n\nテニスボール1つでできるケア方法を\n動画で紹介しています🎾\n\n毎日1分で膝の痛みが変わりますよ！",
    recommendedDuration: { min: 30, max: 55 },
    aspectRatio: "9:16",
    tags: ["中高年", "生活シーン", "道具使用"],
    createdAt: "2026-03-28",
    updatedAt: "2026-03-28",
  },

  // ==========================================
  // 坐骨神経痛
  // ==========================================
  {
    id: "sciatica-sleep-position",
    name: "坐骨神経痛の人の正しい寝方",
    description: "「寝る時の痛み」は切実な悩み。ニッチだがドンピシャで刺さる。",
    symptom: "坐骨神経痛",
    platform: "reels",
    format: "豆知識",
    buzzScore: 4,
    referenceNote: "寝方系は「今夜から実践できる」のでCTR・保存率が高い",
    titlePattern: "坐骨神経痛で夜眠れない人、この寝方に変えてみて",
    hookLine: "坐骨神経痛で夜眠れない人、枕の位置を変えるだけで楽になります。",
    scriptStructure: [
      { type: "hook", text: "坐骨神経痛で夜眠れない人、枕の位置を変えるだけで楽になります", duration: 4, note: "ベッドの横で話す" },
      { type: "problem", text: "仰向けで寝ると神経が圧迫されて痛みが強くなります", duration: 5, note: "仰向けのNG姿勢を見せる" },
      { type: "demonstration", text: "横向きで膝の間にクッションを挟む。これだけ", duration: 20, note: "正しい寝姿勢を実演" },
      { type: "solution", text: "仰向け派の人は膝の下にクッションを入れてください", duration: 10, note: "代替案も提示" },
      { type: "cta", text: "今夜から試してみて。保存しておくと忘れないよ", duration: 5, note: "" },
    ],
    thumbnailTips: "正しい寝姿勢の写真 + 「坐骨神経痛の正しい寝方」テロップ",
    hashtagStrategy: ["#坐骨神経痛", "#寝方", "#睡眠", "#腰痛", "#ヘルニア", "#セルフケア"],
    captionTemplate: "【坐骨神経痛の正しい寝方】\n\n夜、お尻から足にかけての痛みで\n眠れない…という方いませんか？\n\n実は「寝る姿勢」を変えるだけで\nかなり楽になることがあります💤\n\n✅ 横向き＋膝の間にクッション\n✅ 仰向け＋膝下にクッション\n\n今夜から試してみてください！",
    recommendedDuration: { min: 30, max: 50 },
    aspectRatio: "9:16",
    tags: ["生活密着", "今夜から実践", "ニッチ"],
    createdAt: "2026-03-28",
    updatedAt: "2026-03-28",
  },

  // ==========================================
  // 睡眠
  // ==========================================
  {
    id: "sleep-quality-routine",
    name: "寝る前5分で睡眠の質が変わるルーティン",
    description: "睡眠系は全年齢で需要がある。ルーティン形式でシリーズ化しやすい。",
    symptom: "睡眠",
    platform: "reels",
    format: "セルフケア指導",
    buzzScore: 5,
    referenceNote: "「睡眠の質」は年間検索トレンドで常に上位",
    titlePattern: "睡眠の質を上げる寝る前{期間}ルーティン",
    hookLine: "寝つきが悪い人、寝る前にこれを5分やるだけで爆睡できます。",
    scriptStructure: [
      { type: "hook", text: "寝つきが悪い人、寝る前5分でこれやって", duration: 3, note: "ベッドの上で" },
      { type: "demonstration", text: "1つ目：足首をゆっくり回す。血流が良くなって体温が下がりやすくなります", duration: 12, note: "" },
      { type: "demonstration", text: "2つ目：4-7-8呼吸法。4秒吸って、7秒止めて、8秒吐く", duration: 15, note: "呼吸のリズムをテロップで表示" },
      { type: "demonstration", text: "3つ目：首の後ろを温める。ホットタオルを1分当てるだけ", duration: 10, note: "タオルの温め方も見せる" },
      { type: "cta", text: "今夜やってみて。効果あったらコメントで教えて", duration: 5, note: "" },
    ],
    thumbnailTips: "ベッドで目を閉じた穏やかな顔 + 「爆睡できる」テロップ + 月のアイコン",
    hashtagStrategy: ["#睡眠", "#睡眠の質", "#不眠", "#寝つきが悪い", "#ナイトルーティン", "#健康習慣"],
    captionTemplate: "【寝る前5分で睡眠の質が激変】\n\n布団に入っても眠れない...\nそんな人はこの3つを試してみて💤\n\n1️⃣ 足首回し（血流改善）\n2️⃣ 4-7-8呼吸法\n3️⃣ 首の後ろを温める\n\n今夜からできることばかり！\n効果があったらコメントで教えてね😊",
    recommendedDuration: { min: 35, max: 55 },
    aspectRatio: "9:16",
    tags: ["ナイトルーティン", "睡眠改善", "全年齢"],
    createdAt: "2026-03-28",
    updatedAt: "2026-03-28",
  },

  // ==========================================
  // 姿勢改善
  // ==========================================
  {
    id: "posture-wall-check",
    name: "壁立ちで姿勢チェック",
    description: "参加型コンテンツ。「今すぐやってみて」でエンゲージメントが爆上がり。",
    symptom: "姿勢改善",
    platform: "tiktok",
    format: "あるある共感",
    buzzScore: 5,
    referenceNote: "「壁に背中をつけてみて」系は参加率・コメント率が非常に高い",
    titlePattern: "壁に背中をつけてみて。{結果}な人は要注意",
    hookLine: "今すぐ壁に背中をつけてみてください。腰に手が入る人、あなたの姿勢ヤバいです。",
    scriptStructure: [
      { type: "hook", text: "今すぐ壁に背中をつけて。腰に手が入る人ヤバいです", duration: 4, note: "壁に立って実演" },
      { type: "demonstration", text: "正常な姿勢なら手のひら1枚分。こぶし1個入る人は反り腰です", duration: 8, note: "OKとNGを比較" },
      { type: "problem", text: "反り腰は腰痛、膝痛、ぽっこりお腹の原因になります", duration: 6, note: "問題提起" },
      { type: "solution", text: "改善するにはこのストレッチ。腸腰筋を伸ばします", duration: 20, note: "ストレッチ実演" },
      { type: "cta", text: "結果をコメントで教えて！手のひら何枚だった？", duration: 5, note: "参加促進" },
    ],
    thumbnailTips: "壁に立つ人のシルエット + 「腰にこぶし入る人＝反り腰」テロップ + 赤い矢印",
    hashtagStrategy: ["#姿勢", "#姿勢改善", "#反り腰", "#猫背", "#姿勢チェック", "#やってみて"],
    captionTemplate: "【壁立ち姿勢チェック】\n\n壁に背中をぴったりつけてみて！\n\n腰と壁の隙間に...\n👐 手のひら1枚 → 正常\n✊ こぶし1個 → 反り腰\n\n反り腰の人は腰痛・膝痛・ぽっこりお腹の\n原因になっているかも⚠️\n\n結果をコメントで教えて👇",
    recommendedDuration: { min: 30, max: 50 },
    aspectRatio: "9:16",
    tags: ["参加型", "チェック系", "コメント爆増"],
    createdAt: "2026-03-28",
    updatedAt: "2026-03-28",
  },
  {
    id: "posture-beforeafter",
    name: "施術ビフォーアフター（姿勢矯正）",
    description: "ビフォーアフターは最強のコンテンツ。視覚的に変化がわかる姿勢は特に強い。",
    symptom: "姿勢改善",
    platform: "reels",
    format: "施術ビフォーアフター",
    buzzScore: 5,
    referenceNote: "治療院のバズ動画No.1フォーマット。100万再生超え事例多数",
    titlePattern: "【衝撃】姿勢矯正ビフォーアフター｜{期間}でここまで変わる",
    hookLine: "この姿勢が、たった1回の施術でこう変わります。",
    scriptStructure: [
      { type: "hook", text: "この姿勢が1回の施術でこう変わります", duration: 3, note: "ビフォー写真を見せる" },
      { type: "demonstration", text: "（施術シーン）※早送り or ハイライト", duration: 15, note: "施術の一部を見せる。ASMR的な音も効果的" },
      { type: "bridge", text: "施術後...", duration: 2, note: "ドラムロールやSE" },
      { type: "demonstration", text: "（アフター）", duration: 5, note: "同アングルで撮影したアフター。テロップで比較" },
      { type: "cta", text: "姿勢が気になる方はDMかプロフィールのリンクから", duration: 5, note: "" },
    ],
    thumbnailTips: "ビフォーアフター分割画像 + 矢印 + 「1回でここまで変わる」テロップ",
    hashtagStrategy: ["#姿勢矯正", "#ビフォーアフター", "#整体", "#猫背矯正", "#変化"],
    captionTemplate: "【姿勢矯正ビフォーアフター】\n\n猫背が気になっていた患者様。\n1回の施術でここまで変化✨\n\n見た目だけでなく、\n肩こりや頭痛も楽になったとのこと！\n\n姿勢が気になる方は\nお気軽にご相談ください🏥",
    recommendedDuration: { min: 20, max: 40 },
    aspectRatio: "9:16",
    tags: ["ビフォーアフター", "最強フォーマット", "視覚的"],
    createdAt: "2026-03-28",
    updatedAt: "2026-03-28",
  },

  // ==========================================
  // 首こり
  // ==========================================
  {
    id: "neck-smartphone",
    name: "スマホ首解消ストレッチ",
    description: "「スマホ首」は現代の共感ワード。若年層にもリーチできる。",
    symptom: "首こり",
    platform: "tiktok",
    format: "セルフケア指導",
    buzzScore: 5,
    referenceNote: "「スマホ首」は10〜30代にも刺さるキーワード",
    titlePattern: "スマホ首を治す{期間}ストレッチ",
    hookLine: "この動画をスマホで見てるあなた、今まさにスマホ首になってます。",
    scriptStructure: [
      { type: "hook", text: "この動画をスマホで見てるあなた、今スマホ首になってます", duration: 3, note: "スマホを見る姿勢を再現→カメラに向く" },
      { type: "problem", text: "スマホを見る姿勢は首に約27kgの負荷がかかっています", duration: 5, note: "数字をテロップで大きく" },
      { type: "demonstration", text: "このストレッチを30秒。あごを引いて後頭部を押す", duration: 25, note: "" },
      { type: "bridge", text: "首が軽くなったでしょ？", duration: 3, note: "首を回して楽そうな顔" },
      { type: "cta", text: "保存してトイレ休憩の時にやってね", duration: 4, note: "具体的な実践タイミング" },
    ],
    thumbnailTips: "スマホを見る猫背シルエット + 「27kg」の数字 + 首に赤い矢印",
    hashtagStrategy: ["#スマホ首", "#首こり", "#ストレートネック", "#ストレッチ", "#現代病"],
    captionTemplate: "【スマホ首解消ストレッチ】\n\n📱この動画を見てるあなた、\n今まさにスマホ首になってます！\n\nスマホを見る姿勢は\n首に約27kgの負荷がかかるって知ってた？\n\n30秒のストレッチで楽になるよ💪\n保存してトイレ休憩の時にやってね",
    recommendedDuration: { min: 30, max: 45 },
    aspectRatio: "9:16",
    tags: ["若年層", "共感", "現代病"],
    createdAt: "2026-03-28",
    updatedAt: "2026-03-28",
  },

  // ==========================================
  // 汎用（全症状共通）
  // ==========================================
  {
    id: "general-patient-voice",
    name: "患者様の声インタビュー",
    description: "信頼構築の最強コンテンツ。新規患者の不安を解消する。",
    symptom: "その他",
    platform: "youtube",
    format: "患者の声",
    buzzScore: 4,
    referenceNote: "「口コミ」「患者の声」は予約コンバージョンに直結",
    titlePattern: "{症状}で{期間}悩んだ{年代}の{性別}が{結果}した話",
    hookLine: "10年間腰痛に悩み続けた私が、ここに来て3回で楽になりました。",
    scriptStructure: [
      { type: "hook", text: "（患者様）ずっと悩んでいた{症状}が楽になりました", duration: 5, note: "患者様のアップ" },
      { type: "problem", text: "（患者様）きっかけは...（悩みの経緯を話す）", duration: 30, note: "インタビュー形式" },
      { type: "bridge", text: "（施術者）最初に来られた時の状態は...", duration: 15, note: "専門家の補足" },
      { type: "solution", text: "（患者様）施術を受けて...（変化を話す）", duration: 30, note: "" },
      { type: "cta", text: "同じお悩みの方はお気軽にご相談ください", duration: 10, note: "予約導線" },
    ],
    thumbnailTips: "笑顔の患者様 + 「10年の腰痛が3回で！」テロップ + 星評価",
    hashtagStrategy: ["#患者様の声", "#口コミ", "#整体", "#ビフォーアフター", "#改善事例"],
    captionTemplate: "【患者様の声】\n\n{症状}で{期間}お悩みだった{年代}の{性別}。\n\n「最初は半信半疑でしたが、\n施術を受けてみてびっくり！」\n\n同じお悩みの方は\nお気軽にご相談ください🏥",
    recommendedDuration: { min: 60, max: 180 },
    aspectRatio: "16:9",
    tags: ["信頼構築", "コンバージョン", "口コミ"],
    createdAt: "2026-03-28",
    updatedAt: "2026-03-28",
  },
  {
    id: "general-clinic-intro",
    name: "院紹介ショート動画",
    description: "新規患者が最初に見る動画。MEO・GBP投稿にも最適。",
    symptom: "その他",
    platform: "shorts",
    format: "院紹介",
    buzzScore: 3,
    referenceNote: "GBP動画投稿用にも使える。地域名×院名のSEO効果",
    titlePattern: "{地域}の{院名}ってどんなところ？30秒で紹介",
    hookLine: "1分で当院のすべてがわかります。",
    scriptStructure: [
      { type: "hook", text: "{地域}で{症状}にお悩みの方へ", duration: 3, note: "外観or受付のシーン" },
      { type: "demonstration", text: "当院の3つの特徴", duration: 5, note: "テロップで数字を出す" },
      { type: "demonstration", text: "特徴1：{強み1}", duration: 7, note: "施術シーン" },
      { type: "demonstration", text: "特徴2：{強み2}", duration: 7, note: "院内の雰囲気" },
      { type: "demonstration", text: "特徴3：{強み3}", duration: 7, note: "実績・口コミ" },
      { type: "cta", text: "初回限定特別価格をご用意しています", duration: 5, note: "料金・予約情報" },
    ],
    thumbnailTips: "院の外観 + 施術者の笑顔 + 「{地域}No.1」テロップ",
    hashtagStrategy: ["#{地域}", "#{地域}整体", "#整体", "#初回限定", "#院紹介"],
    captionTemplate: "【{院名}のご紹介】\n\n{地域}で{得意症状}の改善に特化した整体院です。\n\n✅ {強み1}\n✅ {強み2}\n✅ {強み3}\n\n初回限定の特別価格をご用意しています！\nお気軽にお問い合わせください📞",
    recommendedDuration: { min: 30, max: 60 },
    aspectRatio: "9:16",
    tags: ["院紹介", "GBP", "MEO", "新規向け"],
    createdAt: "2026-03-28",
    updatedAt: "2026-03-28",
  },

  // ==========================================
  // ダイエット×整体（892万再生の実績あり）
  // ==========================================
  {
    id: "diet-2min-stomp",
    name: "60分歩くよりたった2分！足踏みダイエット",
    description: "ダイエット×整体の掛け合わせ。nobu先生の892万再生動画を参考にした構成。",
    symptom: "ダイエット",
    platform: "shorts",
    format: "セルフケア指導",
    buzzScore: 5,
    referenceNote: "nobu先生の類似動画が892万再生。数字のインパクトが鍵",
    titlePattern: "{時間A}歩くよりたった{時間B}！{手法}で{効果}",
    hookLine: "60分ウォーキングするより、たった2分これやるだけで痩せます。",
    scriptStructure: [
      { type: "hook", text: "60分歩くよりたった2分これやって", duration: 3, note: "数字を指で示す。衝撃的な表情" },
      { type: "problem", text: "実はウォーキングだけでは内臓脂肪は落ちにくいんです", duration: 5, note: "意外性で引きつける" },
      { type: "solution", text: "この足踏みは内臓を刺激して代謝を上げます", duration: 5, note: "メカニズムを簡単に" },
      { type: "demonstration", text: "太ももを高く上げて足踏み。1分×2セット", duration: 30, note: "実演。カウントをテロップで" },
      { type: "bridge", text: "お腹がポカポカしてきたでしょ？それが内臓が動いてる証拠", duration: 5, note: "" },
      { type: "cta", text: "保存して毎朝やってみて。1週間で変わります", duration: 5, note: "" },
    ],
    thumbnailTips: "「60分 vs 2分」の対比テロップ + 体重計の数字 + 驚きの表情",
    hashtagStrategy: ["#ダイエット", "#痩せる", "#足踏み", "#2分ダイエット", "#お腹痩せ"],
    captionTemplate: "【60分歩くよりたった2分】\n\n毎日ウォーキングしてるのに痩せない...\nそんな人はこの足踏みを試してみて！\n\n太ももを高く上げて足踏み\n1分×2セットだけ💪\n\nお腹がポカポカしたら\n内臓が動いてる証拠です✨",
    recommendedDuration: { min: 40, max: 60 },
    aspectRatio: "9:16",
    tags: ["ダイエット", "数字インパクト", "高再生"],
    createdAt: "2026-03-28",
    updatedAt: "2026-03-28",
  },
  {
    id: "diet-pelvic-postpartum",
    name: "産後骨盤ダイエット｜ぽっこりお腹解消",
    description: "産後ママ層に刺さる。共感→解決の流れが重要。",
    symptom: "産後",
    platform: "reels",
    format: "セルフケア指導",
    buzzScore: 5,
    referenceNote: "産後ママのInstagram利用率は80%超。Reelsとの相性が最高",
    titlePattern: "産後のぽっこりお腹、骨盤を整えるだけで変わります",
    hookLine: "産後のぽっこりお腹、何をしても戻らないと思っていませんか？",
    scriptStructure: [
      { type: "hook", text: "産後のぽっこりお腹、骨盤が原因かもしれません", duration: 3, note: "お腹を指して" },
      { type: "problem", text: "出産で開いた骨盤が戻らないと内臓が下がってお腹が出ます", duration: 6, note: "イラストで説明" },
      { type: "demonstration", text: "この骨盤体操を寝ながらやるだけ", duration: 30, note: "赤ちゃんの横でもできる体操" },
      { type: "bridge", text: "寝かしつけの後にこれだけやってみて", duration: 3, note: "具体的なタイミング" },
      { type: "cta", text: "保存して今夜からやってみてね", duration: 4, note: "" },
    ],
    thumbnailTips: "ママのシルエット + 「骨盤を整えるだけ」テロップ + ビフォーアフター矢印",
    hashtagStrategy: ["#産後ダイエット", "#骨盤矯正", "#産後", "#ぽっこりお腹", "#ママ"],
    captionTemplate: "【産後のぽっこりお腹解消法】\n\n何をしてもお腹が戻らない...\nそれは骨盤が原因かも！\n\n出産で開いた骨盤を整えるだけで\nお腹のラインが変わります✨\n\n寝かしつけの後にできる簡単体操👶\n保存して今夜からやってみてね！",
    recommendedDuration: { min: 35, max: 55 },
    aspectRatio: "9:16",
    tags: ["産後", "ママ層", "骨盤", "寝ながら"],
    createdAt: "2026-03-28",
    updatedAt: "2026-03-28",
  },

  // ==========================================
  // 股関節（2,500万再生の実績あり）
  // ==========================================
  {
    id: "hip-flexibility-ultra",
    name: "股関節が超硬い人向けストレッチ",
    description: "オガトレの2,500万再生動画を参考。ターゲット限定が鍵。",
    symptom: "股関節",
    platform: "youtube",
    format: "セルフケア指導",
    buzzScore: 5,
    referenceNote: "オガトレ「開脚」2,500万再生。「超硬い人向け」のターゲティングが秀逸",
    titlePattern: "股関節が「超」硬い人向け！{期間}で柔らかくなるストレッチ",
    hookLine: "股関節が硬くて開脚なんて無理、そう思ってる人だけ見てください。",
    scriptStructure: [
      { type: "hook", text: "股関節が硬くて開脚なんて無理って人、この動画だけ見て", duration: 5, note: "硬い人の開脚を見せる→「大丈夫です」" },
      { type: "bridge", text: "こんにちは、{院名}の{先生名}です。今日は超硬い人向けのストレッチです", duration: 8, note: "" },
      { type: "problem", text: "股関節が硬いと腰痛、膝痛、むくみの原因になります", duration: 15, note: "なぜ柔軟性が重要か" },
      { type: "demonstration", text: "レベル1：座って足裏を合わせる。ゆっくり前に倒す", duration: 60, note: "簡単なものから" },
      { type: "demonstration", text: "レベル2：開脚の準備ストレッチ", duration: 60, note: "段階的に" },
      { type: "demonstration", text: "レベル3：壁を使った開脚", duration: 60, note: "無理のない範囲で" },
      { type: "cta", text: "毎日5分続けると2週間で変わります。チャンネル登録もお願いします", duration: 10, note: "" },
    ],
    thumbnailTips: "開脚のビフォーアフター + 「超硬い人専用」テロップ（黄色背景）+ 驚きの表情",
    hashtagStrategy: ["#股関節", "#開脚", "#ストレッチ", "#柔軟", "#体が硬い"],
    captionTemplate: "【股関節が超硬い人向けストレッチ】\n\n「開脚なんて一生無理」\nそう思っていませんか？\n\n実は正しい順番でストレッチすれば\n誰でも柔らかくなれます！\n\n▼目次\n0:00 はじめに\n0:13 なぜ柔軟性が大事？\n0:28 レベル1\n1:28 レベル2\n2:28 レベル3\n3:28 まとめ",
    recommendedDuration: { min: 180, max: 300 },
    aspectRatio: "16:9",
    tags: ["超高再生", "ターゲット限定", "レベル別"],
    createdAt: "2026-03-28",
    updatedAt: "2026-03-28",
  },
  {
    id: "hip-5sec-stretch",
    name: "5秒でできる股関節ストレッチ",
    description: "5秒で完結する超短時間系。角谷暢大氏の1,230万再生パターン。",
    symptom: "股関節",
    platform: "tiktok",
    format: "セルフケア指導",
    buzzScore: 5,
    referenceNote: "角谷暢大氏が5秒ストレッチで1,230万再生。極端な短時間がバズる",
    titlePattern: "たった5秒！股関節がグッと柔らかくなるストレッチ",
    hookLine: "5秒で股関節が柔らかくなります。嘘だと思ったらやってみて。",
    scriptStructure: [
      { type: "hook", text: "5秒で股関節柔らかくなります。やってみて", duration: 3, note: "自信を持って断言" },
      { type: "demonstration", text: "立った状態で足を前後に開いて、前の膝を曲げる。5秒キープ", duration: 10, note: "シンプルに1つだけ" },
      { type: "bridge", text: "はい、もう一回開脚してみて。さっきより開くでしょ？", duration: 5, note: "変化を体感させる" },
      { type: "cta", text: "保存して毎日やってみて", duration: 3, note: "" },
    ],
    thumbnailTips: "「たった5秒」の大文字 + ストレッチポーズ + 矢印",
    hashtagStrategy: ["#股関節", "#5秒ストレッチ", "#柔軟", "#簡単", "#ストレッチ"],
    captionTemplate: "【5秒で股関節が柔らかくなる】\n\n嘘だと思ったらやってみて！\n\nたった5秒のストレッチで\n股関節の可動域が変わります✨\n\n保存して毎日やってみてね！",
    recommendedDuration: { min: 15, max: 30 },
    aspectRatio: "9:16",
    tags: ["5秒", "超短時間", "TikTok向き"],
    createdAt: "2026-03-28",
    updatedAt: "2026-03-28",
  },

  // ==========================================
  // 肩甲骨はがし（700万再生の実績あり）
  // ==========================================
  {
    id: "scapula-peel-selfcare",
    name: "肩甲骨はがしセルフケア｜ガチガチの人向け",
    description: "山内義弘氏の700万再生動画パターン。独自メソッド感が重要。",
    symptom: "肩甲骨",
    platform: "reels",
    format: "セルフケア指導",
    buzzScore: 5,
    referenceNote: "山内義弘「肩甲骨はがし」700万再生超。姿勢改善ブームで常に需要あり",
    titlePattern: "肩甲骨がガチガチの人、このはがし方を試してみて",
    hookLine: "肩甲骨がガチガチで肩こりが治らない人、この動画保存して。",
    scriptStructure: [
      { type: "hook", text: "肩甲骨ガチガチの人、これ保存して", duration: 3, note: "肩甲骨を動かそうとして動かない様子" },
      { type: "problem", text: "肩甲骨が固まると肩こり、猫背、巻き肩全部の原因になります", duration: 5, note: "" },
      { type: "demonstration", text: "壁に手をついて、体を反対にひねる。肩甲骨がメリメリ動きます", duration: 20, note: "壁を使ったストレッチ" },
      { type: "demonstration", text: "次にタオルを使って。両手で持って頭の後ろに引く", duration: 15, note: "タオルストレッチ" },
      { type: "bridge", text: "肩を回してみて。さっきと全然違うでしょ？", duration: 4, note: "" },
      { type: "cta", text: "保存してお風呂上がりにやってみて", duration: 4, note: "" },
    ],
    thumbnailTips: "背中のアップ + 肩甲骨の位置を矢印で示す + 「ガチガチ解消」テロップ",
    hashtagStrategy: ["#肩甲骨はがし", "#肩甲骨", "#肩こり解消", "#巻き肩", "#猫背"],
    captionTemplate: "【肩甲骨はがしセルフケア】\n\n肩甲骨がガチガチで\n肩こりが治らない人へ💪\n\n壁とタオルがあればOK！\n2つのストレッチで肩甲骨がメリメリ動きます✨\n\nお風呂上がりにやると効果的！\n保存してやってみてね",
    recommendedDuration: { min: 40, max: 60 },
    aspectRatio: "9:16",
    tags: ["肩甲骨はがし", "道具使用", "高再生"],
    createdAt: "2026-03-28",
    updatedAt: "2026-03-28",
  },

  // ==========================================
  // ストレートネック
  // ==========================================
  {
    id: "straight-neck-3sec",
    name: "3秒でストレートネック改善体操",
    description: "迫田和也氏の407万再生パターン。極端な短時間×症状名が最強。",
    symptom: "ストレートネック",
    platform: "shorts",
    format: "セルフケア指導",
    buzzScore: 5,
    referenceNote: "迫田和也「3秒で首コリを消す体操」407万再生。時短訴求×症状名の王道",
    titlePattern: "3秒でストレートネックが改善する体操",
    hookLine: "ストレートネックの人、3秒でこれやってみて。首が軽くなります。",
    scriptStructure: [
      { type: "hook", text: "ストレートネックの人、3秒で首が軽くなります", duration: 3, note: "指を3本立てる" },
      { type: "demonstration", text: "あごを引いて、後頭部を手で押す。3秒キープ", duration: 8, note: "シンプルに1つだけ" },
      { type: "bridge", text: "もう一回首を回してみて。軽くなったでしょ？", duration: 5, note: "変化を体感" },
      { type: "solution", text: "スマホを見る前にこれを1回やるだけで全然違います", duration: 5, note: "日常への落とし込み" },
      { type: "cta", text: "保存してスマホ見る前にやってね", duration: 3, note: "" },
    ],
    thumbnailTips: "「3秒」の大文字（黄色）+ 首を押さえるポーズ + ビフォーアフター矢印",
    hashtagStrategy: ["#ストレートネック", "#スマホ首", "#首こり", "#3秒", "#セルフケア"],
    captionTemplate: "【3秒でストレートネック改善】\n\nスマホの見すぎでストレートネックに...\nそんな人はこの体操を3秒やるだけ！\n\nあごを引いて後頭部を手で押す。\nこれだけで首が軽くなります💡\n\nスマホを見る前の習慣にしてみて！",
    recommendedDuration: { min: 20, max: 30 },
    aspectRatio: "9:16",
    tags: ["3秒", "若年層", "現代病", "超短時間"],
    createdAt: "2026-03-28",
    updatedAt: "2026-03-28",
  },

  // ==========================================
  // 脊柱管狭窄症・ヘルニア
  // ==========================================
  {
    id: "spinal-stenosis-nosurgery",
    name: "脊柱管狭窄症｜手術しなくていい場合とは",
    description: "病名検索で上位表示を狙う。「手術しなくていい」系が強い。",
    symptom: "脊柱管狭窄症",
    platform: "youtube",
    format: "症状解説",
    buzzScore: 4,
    referenceNote: "「脊柱管狭窄症 手術」の検索ボリュームが大きい。シニア層のYouTube利用増",
    titlePattern: "【脊柱管狭窄症】手術が必要な人と必要ない人の違い",
    hookLine: "脊柱管狭窄症と診断されて手術を勧められた方、ちょっと待ってください。",
    scriptStructure: [
      { type: "hook", text: "脊柱管狭窄症で手術を勧められた方、ちょっと待ってください", duration: 5, note: "真剣な表情" },
      { type: "bridge", text: "こんにちは、{院名}の{先生名}です", duration: 8, note: "" },
      { type: "problem", text: "脊柱管狭窄症の3つのタイプを解説します", duration: 60, note: "図解で分かりやすく" },
      { type: "solution", text: "手術が必要な場合と保存療法で改善する場合の見分け方", duration: 90, note: "チェックリスト形式" },
      { type: "demonstration", text: "自宅でできる改善エクササイズ3つ", duration: 90, note: "実演" },
      { type: "cta", text: "不安な方はお気軽にご相談ください。概要欄にリンクがあります", duration: 10, note: "" },
    ],
    thumbnailTips: "「手術しなくていい？」テロップ + 背骨のイラスト + 驚きの表情",
    hashtagStrategy: ["#脊柱管狭窄症", "#腰痛", "#手術", "#整体", "#シニア"],
    captionTemplate: "【脊柱管狭窄症：手術は本当に必要？】\n\n脊柱管狭窄症と診断されて\n手術を勧められた方へ。\n\n実は手術が必要なケースは\n全体の一部です。\n\n▼目次\n0:00 はじめに\n0:13 3つのタイプ\n1:13 手術が必要な場合\n2:43 自宅エクササイズ\n4:13 まとめ",
    recommendedDuration: { min: 240, max: 420 },
    aspectRatio: "16:9",
    tags: ["シニア層", "病名SEO", "教育系"],
    createdAt: "2026-03-28",
    updatedAt: "2026-03-28",
  },
  {
    id: "hernia-ng-stretch",
    name: "ヘルニアの人が絶対やってはいけないストレッチ",
    description: "警告×病名のタイトルパターン。カリギュラ効果で視聴率UP。",
    symptom: "ヘルニア",
    platform: "reels",
    format: "NG行動",
    buzzScore: 5,
    referenceNote: "「やってはいけない」×病名はカリギュラ効果で視聴率が跳ね上がる",
    titlePattern: "【危険】ヘルニアの人が絶対やってはいけないストレッチ",
    hookLine: "ヘルニアの人がこのストレッチをやると悪化します。今すぐやめてください。",
    scriptStructure: [
      { type: "hook", text: "ヘルニアの人、このストレッチ今すぐやめて", duration: 3, note: "手でバツ + 真剣な表情" },
      { type: "problem", text: "前屈ストレッチ、実はヘルニアの人には逆効果なんです", duration: 8, note: "NG動作を見せる" },
      { type: "problem", text: "腰をひねるストレッチもNG。椎間板に圧力がかかります", duration: 8, note: "" },
      { type: "solution", text: "代わりにこのストレッチ。マッケンジー体操と言います", duration: 20, note: "正しいストレッチを実演" },
      { type: "cta", text: "ヘルニアで悩んでる人は保存してね", duration: 4, note: "" },
    ],
    thumbnailTips: "大きなバツマーク + 「絶対やるな」赤文字 + NGストレッチのポーズ",
    hashtagStrategy: ["#ヘルニア", "#椎間板ヘルニア", "#やってはいけない", "#腰痛", "#ストレッチ"],
    captionTemplate: "【ヘルニアの人は絶対やるな】\n\n良かれと思ってやってるそのストレッチ、\nヘルニアを悪化させてるかも⚠️\n\n❌ 前屈ストレッチ\n❌ 腰をひねるストレッチ\n\n代わりにやるべき正しいストレッチを\n動画で紹介しています👆",
    recommendedDuration: { min: 35, max: 55 },
    aspectRatio: "9:16",
    tags: ["NG系", "警告", "病名", "カリギュラ効果"],
    createdAt: "2026-03-28",
    updatedAt: "2026-03-28",
  },

  // ==========================================
  // 小顔・美容整体
  // ==========================================
  {
    id: "kogao-beforeafter",
    name: "小顔矯正ビフォーアフター｜衝撃の変化",
    description: "小顔ビフォーアフターはReels/TikTok最強コンテンツ。視覚インパクト重視。",
    symptom: "小顔・美容",
    platform: "reels",
    format: "施術ビフォーアフター",
    buzzScore: 5,
    referenceNote: "小顔矯正のビフォーアフターは100万再生超え多数。保存率18%",
    titlePattern: "【衝撃】小顔矯正ビフォーアフター｜{期間}でここまで変わる",
    hookLine: "この顔が1回の施術でこう変わります。",
    scriptStructure: [
      { type: "hook", text: "この顔が1回でこう変わります", duration: 2, note: "アフター写真をチラ見せ" },
      { type: "demonstration", text: "（ビフォー）施術前の状態", duration: 3, note: "正面・横からの撮影" },
      { type: "demonstration", text: "（施術シーン）フェイスラインを整えていきます", duration: 15, note: "ASMR的な施術音も効果的" },
      { type: "bridge", text: "施術後...", duration: 2, note: "SE・トランジション" },
      { type: "demonstration", text: "（アフター）", duration: 5, note: "同アングルで比較。テロップで変化を強調" },
      { type: "cta", text: "小顔になりたい方はDMかプロフィールから", duration: 3, note: "" },
    ],
    thumbnailTips: "左右分割のビフォーアフター + 矢印 + 「1回でこの変化」テロップ",
    hashtagStrategy: ["#小顔矯正", "#小顔", "#ビフォーアフター", "#美容整体", "#フェイスライン"],
    captionTemplate: "【小顔矯正ビフォーアフター】\n\n1回の施術でここまで変わりました✨\n\nフェイスラインがスッキリ！\nお顔のむくみ・エラ張りが気になる方は\nお気軽にご相談ください💆‍♀️",
    recommendedDuration: { min: 20, max: 35 },
    aspectRatio: "9:16",
    tags: ["ビフォーアフター", "美容", "高保存率", "最強フォーマット"],
    createdAt: "2026-03-28",
    updatedAt: "2026-03-28",
  },
  {
    id: "kogao-selfcare-5sec",
    name: "5秒で小顔になるセルフマッサージ",
    description: "美容×5秒の組み合わせ。女性層の保存率が極めて高い。",
    symptom: "小顔・美容",
    platform: "tiktok",
    format: "セルフケア指導",
    buzzScore: 5,
    referenceNote: "「整形級に綺麗になれる」系の変身コンテンツは女性層でバズりやすい",
    titlePattern: "5秒で小顔になるマッサージ｜整形級の変化",
    hookLine: "5秒で顔が変わります。嘘だと思ったらやってみて。",
    scriptStructure: [
      { type: "hook", text: "5秒で顔変わります。やってみて", duration: 2, note: "自信を持って断言" },
      { type: "demonstration", text: "耳の下のリンパを5秒押す。ぐーっと", duration: 8, note: "手の位置をアップで" },
      { type: "bridge", text: "鏡見てみて。フェイスラインが変わってるでしょ？", duration: 5, note: "鏡で確認する映像" },
      { type: "cta", text: "朝のメイク前にやると1日持ちます。保存してね", duration: 5, note: "" },
    ],
    thumbnailTips: "「5秒で小顔」大文字 + フェイスライン矢印 + 驚きの表情",
    hashtagStrategy: ["#小顔", "#小顔マッサージ", "#5秒", "#美容", "#フェイスライン"],
    captionTemplate: "【5秒で小顔になるマッサージ】\n\n耳の下のリンパを5秒押すだけ！\nフェイスラインがスッキリ✨\n\n朝のメイク前にやると\n1日中小顔が持続します💆‍♀️\n\n保存してやってみてね！",
    recommendedDuration: { min: 15, max: 25 },
    aspectRatio: "9:16",
    tags: ["5秒", "美容", "女性層", "TikTok向き"],
    createdAt: "2026-03-28",
    updatedAt: "2026-03-28",
  },

  // ==========================================
  // 美容鍼
  // ==========================================
  {
    id: "biyohari-asmr",
    name: "美容鍼ASMR｜顔に鍼を打つ瞬間",
    description: "顔に鍼を打つビジュアルインパクトで好奇心を刺激。ASMR系で再生数を稼ぐ。",
    symptom: "美容鍼",
    platform: "tiktok",
    format: "ASMR施術",
    buzzScore: 5,
    referenceNote: "美容鍼のビジュアルインパクト + ASMR音が中毒性を生む。ループ再生されやすい",
    titlePattern: "美容鍼100本打ってみた｜衝撃のビフォーアフター",
    hookLine: "顔に鍼を100本打ちます。",
    scriptStructure: [
      { type: "hook", text: "顔に鍼を100本打ちます", duration: 2, note: "鍼を見せる。衝撃的" },
      { type: "demonstration", text: "（施術シーン）鍼を打つ音と映像", duration: 20, note: "ASMR。鍼を打つ音をクリアに" },
      { type: "bridge", text: "100本完了", duration: 3, note: "鍼が刺さった顔の全体像" },
      { type: "demonstration", text: "（アフター）鍼を外した後の肌", duration: 5, note: "肌ツヤの変化" },
      { type: "cta", text: "美容鍼気になる方はプロフィールから", duration: 3, note: "" },
    ],
    thumbnailTips: "顔に鍼が刺さった状態の写真 + 「100本」の数字 + ビフォーアフター",
    hashtagStrategy: ["#美容鍼", "#鍼灸", "#ASMR", "#美肌", "#エイジングケア"],
    captionTemplate: "【美容鍼100本】\n\n顔に鍼を100本打ちました！\n\n鍼を打つことで血流が良くなり\n肌のハリ・ツヤがUP✨\n\n施術後の肌の違い、\n動画で確認してみてください💆‍♀️",
    recommendedDuration: { min: 25, max: 40 },
    aspectRatio: "9:16",
    tags: ["ASMR", "美容鍼", "ビジュアルインパクト", "ループ再生"],
    createdAt: "2026-03-28",
    updatedAt: "2026-03-28",
  },

  // ==========================================
  // ASMR施術（ボキボキ系）
  // ==========================================
  {
    id: "asmr-bokiboki-fullbody",
    name: "ボキボキ整体ASMR｜全身骨格矯正",
    description: "ボキボキ音のASMR系は最もバズりやすいジャンル。ループ再生で再生数爆増。",
    symptom: "その他",
    platform: "shorts",
    format: "ASMR施術",
    buzzScore: 5,
    referenceNote: "ボキボキ整体はTikTok/Shorts最強コンテンツ。テレビでも芸能人が受けて話題",
    titlePattern: "【ASMR】全身ボキボキ骨格矯正｜気持ちよすぎる音",
    hookLine: "この音、気持ちよすぎません？",
    scriptStructure: [
      { type: "hook", text: "（ボキっという音からスタート）", duration: 2, note: "音から始める。テロップなし" },
      { type: "demonstration", text: "首の矯正", duration: 8, note: "ボキボキ音をクリアに収録" },
      { type: "demonstration", text: "背中の矯正", duration: 8, note: "" },
      { type: "demonstration", text: "腰の矯正", duration: 8, note: "" },
      { type: "bridge", text: "全身スッキリ", duration: 3, note: "患者の楽になった表情" },
      { type: "cta", text: "ボキボキ整体体験してみたい方はプロフィールから", duration: 3, note: "" },
    ],
    thumbnailTips: "骨格矯正の瞬間の写真 + 「ボキボキ」テロップ + 音波マーク",
    hashtagStrategy: ["#ボキボキ整体", "#ほね音", "#ASMR", "#骨格矯正", "#整体"],
    captionTemplate: "【ボキボキ整体ASMR】\n\n全身骨格矯正の音、\n気持ちよすぎません？🦴\n\nイヤホンで聴くと最高です🎧\n\n体験してみたい方は\nお気軽にご連絡ください！",
    recommendedDuration: { min: 25, max: 40 },
    aspectRatio: "9:16",
    tags: ["ASMR", "ボキボキ", "ループ再生", "最強バズ"],
    createdAt: "2026-03-28",
    updatedAt: "2026-03-28",
  },

  // ==========================================
  // 五十肩
  // ==========================================
  {
    id: "frozen-shoulder-selfcheck",
    name: "五十肩セルフチェック｜腕が上がらない人へ",
    description: "「腕が上がらない」という具体的シーンで切り取る。中高年層に刺さる。",
    symptom: "五十肩",
    platform: "reels",
    format: "セルフケア指導",
    buzzScore: 4,
    referenceNote: "40-60代の「腕が上がらない」悩みは切実。保存率が高い",
    titlePattern: "腕が上がらない人、五十肩かも？セルフチェック＆改善法",
    hookLine: "腕が上がらなくなった人、それ五十肩かもしれません。",
    scriptStructure: [
      { type: "hook", text: "腕が上がらなくなった人、五十肩かも", duration: 3, note: "腕を上げようとして痛そうな表情" },
      { type: "demonstration", text: "チェック1：腕を真横に上げてみて。90度以上上がらない人は要注意", duration: 8, note: "" },
      { type: "demonstration", text: "チェック2：背中で手を組んでみて。組めない人はかなり進行してます", duration: 8, note: "" },
      { type: "solution", text: "このストレッチを毎日やって。壁に手をついて体を回す", duration: 20, note: "痛くない範囲で" },
      { type: "cta", text: "五十肩で悩んでる人は保存してね", duration: 4, note: "" },
    ],
    thumbnailTips: "腕を上げようとする人 + 赤い痛みマーク + 「五十肩チェック」テロップ",
    hashtagStrategy: ["#五十肩", "#腕が上がらない", "#セルフチェック", "#40代", "#50代"],
    captionTemplate: "【五十肩セルフチェック】\n\n最近腕が上がりにくい...\nそれは五十肩のサインかも⚠️\n\n✅ 腕が90度以上上がらない\n✅ 背中で手が組めない\n\n当てはまった人は\n動画のストレッチを毎日やってみて！",
    recommendedDuration: { min: 35, max: 50 },
    aspectRatio: "9:16",
    tags: ["中高年", "セルフチェック", "五十肩"],
    createdAt: "2026-03-28",
    updatedAt: "2026-03-28",
  },

  // ==========================================
  // ぎっくり腰
  // ==========================================
  {
    id: "gikkuri-emergency",
    name: "ぎっくり腰になった時の応急処置",
    description: "「今まさに痛い」人が検索する。緊急性の高い検索意図に応える。",
    symptom: "ぎっくり腰",
    platform: "shorts",
    format: "豆知識",
    buzzScore: 4,
    referenceNote: "「ぎっくり腰 なったら」の検索は常に高い。即効性コンテンツ",
    titlePattern: "ぎっくり腰になった！今すぐやるべき3つのこと",
    hookLine: "ぎっくり腰になった人、まず動かないで。この3つだけやって。",
    scriptStructure: [
      { type: "hook", text: "ぎっくり腰になった人、まず動かないで", duration: 3, note: "真剣な表情で" },
      { type: "demonstration", text: "1. 横向きで膝を抱えて安静。まず痛みを落ち着かせる", duration: 10, note: "楽な姿勢を実演" },
      { type: "demonstration", text: "2. アイシング。氷嚢を腰に15分当てる", duration: 8, note: "" },
      { type: "demonstration", text: "3. 2日以上動けなかったらすぐ専門家へ", duration: 8, note: "受診の目安" },
      { type: "cta", text: "保存しておくと、いざという時に役立ちます", duration: 5, note: "" },
    ],
    thumbnailTips: "腰を押さえて倒れる人 + 「緊急」赤テロップ + 「3つの応急処置」",
    hashtagStrategy: ["#ぎっくり腰", "#腰痛", "#応急処置", "#緊急", "#整体"],
    captionTemplate: "【ぎっくり腰の応急処置】\n\nぎっくり腰になったら\nまずこの3つ！\n\n1️⃣ 横向き安静（膝を抱える）\n2️⃣ アイシング15分\n3️⃣ 2日以上動けなければ受診\n\nいざという時のために保存しておこう🏥",
    recommendedDuration: { min: 30, max: 45 },
    aspectRatio: "9:16",
    tags: ["緊急", "応急処置", "検索意図一致"],
    createdAt: "2026-03-28",
    updatedAt: "2026-03-28",
  },

  // ==========================================
  // 冷え性
  // ==========================================
  {
    id: "cold-hands-feet",
    name: "手足の冷えが消える｜寝る前1分ケア",
    description: "冷え性は女性の大半が悩む。季節問わず需要あり。",
    symptom: "冷え性",
    platform: "reels",
    format: "セルフケア指導",
    buzzScore: 4,
    referenceNote: "「冷えの放置は老けて見える」というフック付き動画が100万再生超え",
    titlePattern: "手足が冷たい人、寝る前にこれ1分やって",
    hookLine: "冷え性を放置すると老けて見えるって知っていましたか？",
    scriptStructure: [
      { type: "hook", text: "冷えを放置すると老けて見えるって知ってた？", duration: 3, note: "フックで恐怖を煽る" },
      { type: "problem", text: "血流が悪いと肌のターンオーバーが遅れて、くすみ・たるみの原因に", duration: 6, note: "" },
      { type: "demonstration", text: "足指グーパー運動。20回やるだけで足がポカポカします", duration: 20, note: "" },
      { type: "demonstration", text: "ふくらはぎマッサージ。下から上にさする。30秒", duration: 15, note: "" },
      { type: "bridge", text: "足先が温かくなったでしょ？これで寝つきも良くなります", duration: 4, note: "" },
      { type: "cta", text: "保存して寝る前にやってみてね", duration: 4, note: "" },
    ],
    thumbnailTips: "冷えた足のイメージ + 「冷え→老ける」テロップ + ビフォーアフター",
    hashtagStrategy: ["#冷え性", "#冷え改善", "#足の冷え", "#温活", "#美容"],
    captionTemplate: "【冷え性を放置すると老ける？】\n\n手足が冷たい人、要注意！\n\n冷え → 血流低下 → 肌のくすみ・たるみ\nつまり老けて見える原因に⚠️\n\n寝る前1分のケアで改善できます✨\n\n保存して今夜からやってみて！",
    recommendedDuration: { min: 40, max: 60 },
    aspectRatio: "9:16",
    tags: ["冷え性", "女性層", "美容", "恐怖フック"],
    createdAt: "2026-03-28",
    updatedAt: "2026-03-28",
  },

  // ==========================================
  // 汎用（プラットフォーム特化テンプレート）
  // ==========================================
  {
    id: "general-clinic-tour",
    name: "院内ツアー30秒｜こんなところです",
    description: "松下展平氏推奨の「最初に作るべき4本」の1つ。新規患者の不安解消に直結。",
    symptom: "その他",
    platform: "shorts",
    format: "院内ツアー",
    buzzScore: 3,
    referenceNote: "松下展平氏推奨。院内の雰囲気が分かる動画は来院ハードルを下げる",
    titlePattern: "{地域}の{院名}ってどんなところ？30秒で院内ツアー",
    hookLine: "うちの院の中、全部見せます。",
    scriptStructure: [
      { type: "hook", text: "{院名}の中、全部見せます", duration: 2, note: "入口から撮影開始" },
      { type: "demonstration", text: "受付→待合室", duration: 5, note: "清潔感・明るさを意識" },
      { type: "demonstration", text: "施術スペース", duration: 8, note: "ベッド・設備を見せる" },
      { type: "demonstration", text: "施術の様子（ダイジェスト）", duration: 8, note: "実際に施術しているシーン" },
      { type: "cta", text: "初めての方も安心してお越しください", duration: 5, note: "笑顔で" },
    ],
    thumbnailTips: "院の外観 + 「全部見せます」テロップ + 院長の笑顔",
    hashtagStrategy: ["#{地域}", "#{地域}整体", "#院内ツアー", "#整体院", "#初めての方"],
    captionTemplate: "【院内ツアー】\n\n{院名}の中を全部お見せします！\n\n初めての方も安心してお越しいただけるよう\n院内の雰囲気をお届け✨\n\n気になった方は\nお気軽にお問い合わせください！",
    recommendedDuration: { min: 25, max: 40 },
    aspectRatio: "9:16",
    tags: ["院内ツアー", "新規獲得", "GBP", "MEO"],
    createdAt: "2026-03-28",
    updatedAt: "2026-03-28",
  },
  {
    id: "general-fullcut-treatment",
    name: "ノーカット施術動画｜初回の流れ",
    description: "30分〜1時間のノーカット動画。やっている院がほぼないため差別化になる。",
    symptom: "その他",
    platform: "youtube",
    format: "ノーカット施術",
    buzzScore: 3,
    referenceNote: "松下展平氏推奨。ノーカット施術は疑似来院体験。競合がほぼやっていない差別化コンテンツ",
    titlePattern: "【ノーカット】{院名}の施術を全部お見せします｜問診→施術→アドバイス",
    hookLine: "当院の施術の流れを、問診から最後のアドバイスまで全てノーカットでお見せします。",
    scriptStructure: [
      { type: "hook", text: "今日は施術の全てをノーカットでお見せします", duration: 5, note: "" },
      { type: "bridge", text: "まず問診票の記入から", duration: 30, note: "受付シーン" },
      { type: "demonstration", text: "問診：お悩みの聞き取り", duration: 180, note: "実際の会話" },
      { type: "demonstration", text: "検査：体の状態をチェック", duration: 120, note: "" },
      { type: "demonstration", text: "施術", duration: 600, note: "実際の施術" },
      { type: "demonstration", text: "施術後の説明・セルフケアアドバイス", duration: 180, note: "" },
      { type: "cta", text: "気になった方は概要欄から", duration: 10, note: "" },
    ],
    thumbnailTips: "「全部見せます」テロップ + 施術風景 + 「ノーカット」バッジ",
    hashtagStrategy: ["#整体", "#施術", "#ノーカット", "#初めての整体", "#{地域}"],
    captionTemplate: "【ノーカット施術動画】\n\n問診から施術、セルフケアアドバイスまで\n全ての流れをノーカットでお見せします。\n\n「整体って何をするの？」\nそんな不安を解消する動画です！\n\n▼ご予約はこちら\n{予約URL}",
    recommendedDuration: { min: 1200, max: 3600 },
    aspectRatio: "16:9",
    tags: ["ノーカット", "差別化", "新規安心", "長尺"],
    createdAt: "2026-03-28",
    updatedAt: "2026-03-28",
  },
  {
    id: "general-qa-yahoo",
    name: "整体師が答える！よくある質問Q&A",
    description: "Yahoo知恵袋やコメント欄の質問に答える。ネタ切れしない最強フォーマット。",
    symptom: "その他",
    platform: "youtube",
    format: "Q&A",
    buzzScore: 4,
    referenceNote: "患者の質問に答え続ければネタは無限。迫田和也氏の手法",
    titlePattern: "【Q&A】{質問}？整体師が本音で答えます",
    hookLine: "よくいただく質問に答えます。今日は「{質問}」について。",
    scriptStructure: [
      { type: "hook", text: "「{質問}」よくいただくこの質問、本音で答えます", duration: 5, note: "質問をテロップで表示" },
      { type: "bridge", text: "こんにちは、{院名}の{先生名}です", duration: 5, note: "" },
      { type: "problem", text: "結論から言うと...（明確な答え）", duration: 10, note: "まず結論を先に" },
      { type: "solution", text: "その理由を3つ説明します", duration: 90, note: "根拠を解説" },
      { type: "demonstration", text: "具体的にはこうしてください", duration: 60, note: "実践方法" },
      { type: "cta", text: "質問はコメント欄で受付中。概要欄から予約もできます", duration: 10, note: "" },
    ],
    thumbnailTips: "「？」マーク大きく + 質問テキスト + 考える顔の施術者",
    hashtagStrategy: ["#整体", "#Q&A", "#よくある質問", "#健康", "#セルフケア"],
    captionTemplate: "【整体師が本音で答えるQ&A】\n\nQ.「{質問}」\n\n結論：{回答の要約}\n\n詳しくは動画で解説しています💡\n\n▼質問募集中！\nコメント欄にお気軽にどうぞ📝",
    recommendedDuration: { min: 120, max: 300 },
    aspectRatio: "16:9",
    tags: ["Q&A", "ネタ切れ防止", "エンゲージメント"],
    createdAt: "2026-03-28",
    updatedAt: "2026-03-28",
  },
  {
    id: "general-aruaru-patient",
    name: "整体師あるある｜患者さんがよく言うセリフ",
    description: "あるある系はコメント爆増。エンタメ要素でフォロワー獲得に最適。",
    symptom: "その他",
    platform: "tiktok",
    format: "あるある共感",
    buzzScore: 5,
    referenceNote: "あるある系はTikTokで最もコメント率が高いフォーマットの一つ",
    titlePattern: "整体師あるある｜患者さんがよく言うセリフTOP{数}",
    hookLine: "整体師やってると必ず言われるセリフ、共感したらいいねしてね。",
    scriptStructure: [
      { type: "hook", text: "整体師が必ず言われるセリフ。共感したらいいね", duration: 3, note: "カメラ目線" },
      { type: "demonstration", text: "「先生の手、温かいですね〜」", duration: 5, note: "再現演技" },
      { type: "demonstration", text: "「ここ押すと痛気持ちいい」", duration: 5, note: "" },
      { type: "demonstration", text: "「もっと強くていいですよ」", duration: 5, note: "" },
      { type: "demonstration", text: "「あ、そこそこそこ！」", duration: 5, note: "" },
      { type: "demonstration", text: "「終わった後めっちゃ眠い」", duration: 5, note: "" },
      { type: "cta", text: "他にもある？コメントで教えて", duration: 4, note: "コメント促進" },
    ],
    thumbnailTips: "吹き出し + あるあるセリフ + 苦笑いの施術者",
    hashtagStrategy: ["#整体師あるある", "#あるある", "#整体", "#共感", "#治療家あるある"],
    captionTemplate: "【整体師あるある】\n\n患者さんがよく言うセリフ🤣\n\n「先生の手、温かいですね〜」\n「もっと強くていいですよ」\n「あ、そこそこそこ！」\n\n他にもある？コメントで教えて👇",
    recommendedDuration: { min: 25, max: 40 },
    aspectRatio: "9:16",
    tags: ["あるある", "コメント爆増", "エンタメ", "フォロワー獲得"],
    createdAt: "2026-03-28",
    updatedAt: "2026-03-28",
  },
  {
    id: "general-pronotdo",
    name: "整体師が絶対やらない健康法3選",
    description: "「プロがやらない」系は権威性×カリギュラ効果で最強。",
    symptom: "その他",
    platform: "reels",
    format: "NG行動",
    buzzScore: 5,
    referenceNote: "「整体師が絶対やらない」系は権威性とカリギュラ効果の二重バズ",
    titlePattern: "整体師が絶対やらない健康法{数}選",
    hookLine: "整体師の私が絶対にやらない健康法、3つ教えます。",
    scriptStructure: [
      { type: "hook", text: "整体師の私が絶対やらない健康法3つ", duration: 3, note: "バツ印を手で作る" },
      { type: "demonstration", text: "1つ目：骨盤ベルト。依存すると筋力が落ちます", duration: 10, note: "" },
      { type: "demonstration", text: "2つ目：ぶら下がり健康器。腰痛の人は逆効果の場合が", duration: 10, note: "" },
      { type: "demonstration", text: "3つ目：YouTubeの激しいストレッチ。自分に合ってないと危険", duration: 10, note: "自虐ネタとして笑いも取れる" },
      { type: "solution", text: "じゃあ何がいいか？答えは次の動画で", duration: 4, note: "シリーズ化" },
      { type: "cta", text: "フォローして待っててね", duration: 3, note: "" },
    ],
    thumbnailTips: "腕でバツを作る施術者 + 「絶対やらない」赤テロップ + 健康グッズ",
    hashtagStrategy: ["#整体師", "#やらない", "#健康法", "#NG", "#プロが教える"],
    captionTemplate: "【整体師が絶対やらない健康法】\n\n良かれと思ってるそれ、\nプロは絶対やりません⚠️\n\n1️⃣ 骨盤ベルト\n2️⃣ ぶら下がり健康器\n3️⃣ 合ってないストレッチ\n\n理由は動画で解説！\nじゃあ何がいいの？→次の動画で👆",
    recommendedDuration: { min: 35, max: 50 },
    aspectRatio: "9:16",
    tags: ["プロがやらない", "権威性", "カリギュラ効果", "シリーズ化"],
    createdAt: "2026-03-28",
    updatedAt: "2026-03-28",
  },
  {
    id: "general-hospital-nottell",
    name: "病院では教えてくれない○○の本当の原因",
    description: "「敵設定」パターン。病院vs整体の対比で応援者を獲得する。",
    symptom: "その他",
    platform: "youtube",
    format: "症状解説",
    buzzScore: 5,
    referenceNote: "「病院では教えてくれない」は損失回避バイアス+対比構造の最強タイトル",
    titlePattern: "病院では教えてくれない{症状}の本当の原因と治し方",
    hookLine: "病院で「異常なし」と言われたのに痛い。その理由、教えます。",
    scriptStructure: [
      { type: "hook", text: "病院で異常なしと言われたのに痛い。その理由教えます", duration: 5, note: "共感→解決の約束" },
      { type: "bridge", text: "こんにちは、{院名}の{先生名}です", duration: 5, note: "" },
      { type: "problem", text: "病院の検査では見つけられない痛みの原因があります", duration: 30, note: "なぜ見つからないかを解説" },
      { type: "solution", text: "本当の原因は筋膜・関節の機能障害であることが多い", duration: 60, note: "" },
      { type: "demonstration", text: "自分で確認する方法と改善エクササイズ", duration: 90, note: "" },
      { type: "cta", text: "一人で悩まずご相談ください。概要欄から予約できます", duration: 10, note: "" },
    ],
    thumbnailTips: "「病院では教えてくれない」赤テロップ + 悩む人のシルエット + 矢印で原因を示す",
    hashtagStrategy: ["#病院では教えてくれない", "#{症状}", "#本当の原因", "#整体", "#セルフケア"],
    captionTemplate: "【病院では教えてくれない{症状}の原因】\n\n病院で「異常なし」と言われたのに\nずっと痛い...\n\nそんな経験ありませんか？\n\n実は病院の検査では見つけられない\n痛みの原因があります。\n\n動画で詳しく解説しています💡",
    recommendedDuration: { min: 180, max: 360 },
    aspectRatio: "16:9",
    tags: ["敵設定", "対比構造", "SEO", "信頼構築"],
    createdAt: "2026-03-28",
    updatedAt: "2026-03-28",
  },

  // ==========================================
  // めまい
  // ==========================================
  {
    id: "dizziness-autonomic",
    name: "めまいの原因は首？自律神経との関係",
    description: "めまいは原因不明と言われがち。「本当の原因」系で刺さる。",
    symptom: "めまい",
    platform: "reels",
    format: "症状解説",
    buzzScore: 4,
    referenceNote: "耳鼻科専門鍼灸師GAKU先生がニッチ特化で14.6万人。めまいは検索需要が高い",
    titlePattern: "めまいの本当の原因は首にあった？自律神経との意外な関係",
    hookLine: "めまいがなかなか治らない人、原因は耳じゃなくて首かもしれません。",
    scriptStructure: [
      { type: "hook", text: "めまいが治らない人、原因は耳じゃなくて首かも", duration: 3, note: "首を指して" },
      { type: "problem", text: "首の筋肉が固まると自律神経が乱れてめまいが起きます", duration: 8, note: "" },
      { type: "demonstration", text: "首の後ろ、この部分をゆっくりほぐしてみて", duration: 20, note: "セルフマッサージ実演" },
      { type: "bridge", text: "ほぐした後、頭がスッキリしませんか？", duration: 4, note: "" },
      { type: "cta", text: "めまいで悩んでる人は保存してね", duration: 4, note: "" },
    ],
    thumbnailTips: "めまいのイメージ（ぐるぐる） + 首→脳の矢印 + 「原因は首？」テロップ",
    hashtagStrategy: ["#めまい", "#自律神経", "#首こり", "#ふらつき", "#セルフケア"],
    captionTemplate: "【めまいの原因は首にあった？】\n\nめまいがなかなか治らない...\n耳鼻科に行っても異常なし...\n\n実は首の筋肉が原因かもしれません！\n\n首をほぐすだけでスッキリすることも💡\n動画でセルフケア法を紹介しています",
    recommendedDuration: { min: 30, max: 50 },
    aspectRatio: "9:16",
    tags: ["めまい", "ニッチ", "自律神経", "首"],
    createdAt: "2026-03-28",
    updatedAt: "2026-03-28",
  },

  // ==========================================
  // エステ・美容サロン向け
  // ==========================================
  {
    id: "beauty-skincare-mistake",
    name: "やりがちだけど逆効果なスキンケア3選",
    description: "NGあるある系はエステサロンで最も伸びるフォーマット。視聴完了率76%。",
    symptom: "小顔・美容",
    platform: "reels",
    format: "NG行動",
    buzzScore: 5,
    referenceNote: "間違い訂正系は視聴完了率76%。エステ・美容系で最も伸びる",
    titlePattern: "やりがちだけど逆効果なスキンケア{数}選｜エステティシャンが教える",
    hookLine: "毎日やってるそのスキンケア、実は肌を傷めてます。",
    scriptStructure: [
      { type: "hook", text: "毎日やってるそのスキンケア、肌傷めてます", duration: 3, note: "手でバツ" },
      { type: "demonstration", text: "1. ゴシゴシ洗顔。摩擦でシミ・たるみの原因に", duration: 10, note: "" },
      { type: "demonstration", text: "2. 化粧水のパッティング。叩くのNG、押さえるのが正解", duration: 10, note: "" },
      { type: "demonstration", text: "3. シートマスク長時間放置。逆に水分が蒸発します", duration: 10, note: "" },
      { type: "solution", text: "正しいやり方はこう。優しく、押さえるように", duration: 10, note: "正しい方法を実演" },
      { type: "cta", text: "保存して毎日のケアに活かしてね", duration: 4, note: "" },
    ],
    thumbnailTips: "「逆効果」赤テロップ + スキンケアアイテム + バツマーク",
    hashtagStrategy: ["#スキンケア", "#美肌", "#逆効果", "#エステ", "#美容"],
    captionTemplate: "【逆効果なスキンケア3選】\n\n良かれと思ってやってるそれ、\n実は肌を傷めてるかも⚠️\n\n❌ ゴシゴシ洗顔\n❌ 化粧水パッティング\n❌ シートマスク長時間\n\n正しいケア方法は動画で✨\n保存して毎日のケアに活かしてね！",
    recommendedDuration: { min: 40, max: 60 },
    aspectRatio: "9:16",
    tags: ["美容", "NG系", "エステ", "スキンケア", "高完了率"],
    createdAt: "2026-03-28",
    updatedAt: "2026-03-28",
  },
  {
    id: "beauty-customer-interview",
    name: "お客様インタビュー｜エステ施術後の感想",
    description: "お客様インタビューの定型テンプレート。信頼構築に直結。",
    symptom: "小顔・美容",
    platform: "reels",
    format: "患者の声",
    buzzScore: 4,
    referenceNote: "お客様インタビューの定型質問形式。エステサロンの3大テンプレートの1つ",
    titlePattern: "お客様の声｜{メニュー名}を受けた感想",
    hookLine: "今日の施術、いかがでしたか？",
    scriptStructure: [
      { type: "hook", text: "施術を受けたお客様にインタビュー", duration: 2, note: "テロップで「お客様の声」" },
      { type: "problem", text: "Q: 施術前のお悩みは？", duration: 10, note: "自然な会話形式" },
      { type: "demonstration", text: "Q: 実際に受けてみていかがでしたか？", duration: 10, note: "" },
      { type: "bridge", text: "Q: 満足度は100点中何点？", duration: 5, note: "数字で聞くとインパクト" },
      { type: "cta", text: "Q: 同じ悩みの人にメッセージを！", duration: 8, note: "共感を生む" },
    ],
    thumbnailTips: "笑顔のお客様 + 「満足度100点」テロップ + 星マーク",
    hashtagStrategy: ["#お客様の声", "#口コミ", "#エステ", "#美容", "#満足度"],
    captionTemplate: "【お客様の声】\n\n{メニュー名}を受けたお客様に\n感想をいただきました✨\n\n「{一言感想}」\n\n満足度：{点数}点！\n\n同じお悩みの方は\nお気軽にご相談ください💆‍♀️",
    recommendedDuration: { min: 30, max: 50 },
    aspectRatio: "9:16",
    tags: ["お客様の声", "インタビュー", "信頼構築", "エステ"],
    createdAt: "2026-03-28",
    updatedAt: "2026-03-28",
  },
];

// ===== フィルタリング・検索ヘルパー =====

export function filterTemplates(opts: {
  symptom?: string;
  platform?: string;
  format?: string;
  tag?: string;
}): ViralTemplate[] {
  return VIRAL_TEMPLATES.filter((t) => {
    if (opts.symptom && opts.symptom !== "すべて" && t.symptom !== opts.symptom) return false;
    if (opts.platform && opts.platform !== "all" && t.platform !== opts.platform) return false;
    if (opts.format && opts.format !== "すべて" && t.format !== opts.format) return false;
    if (opts.tag && !t.tags.includes(opts.tag)) return false;
    return true;
  });
}

export function getSymptomCategories(): string[] {
  const set = new Set(VIRAL_TEMPLATES.map((t) => t.symptom));
  return ["すべて", ...Array.from(set)];
}

export function getFormatCategories(): string[] {
  const set = new Set(VIRAL_TEMPLATES.map((t) => t.format));
  return ["すべて", ...Array.from(set)];
}

export function getAllTags(): string[] {
  const set = new Set(VIRAL_TEMPLATES.flatMap((t) => t.tags));
  return Array.from(set);
}
